### ISSUE TITLE
What does typeof groupId === 'string' have to do with theme?

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#5]
In the add function, there is a check if groupId equals string then set the this.config.theme. 
What relation does a groupID have to theme? 
Why does this only apply when groupId is a string ?

It's possible for theme to be undefined here so if groupID is a string then this.config.theme could be undefined. Is that intended behavior ?

```
  add(
    notation, 
    groupId, 
    theme,
  ) {
		if(typeof groupId === 'string' || theme) {
			this.config.theme = theme
		}

```

**Comment by frankieali** [comment]
This was originally done to make groupId an optional parameter and is a habit carried over from my jQuery days. It's mostly a connivance in order to omit optional function arguments. In this case you could call this method using `add('2d20','purple')` to add two purple dice without having to specify the groupId or pass an empty or null second argument to the function. This probably does not translate to typescript very well because it will coerce the argument type. In most other functions I pass arguments as a single object.
Also, it looks like my intent of assign the second argument to `this.config.theme` wouldn't work anyway. Perhaps it's a remanent of a previous refactor. I'll clean this up. Thanks for pointing it out.

**Comment by clevett** [comment]
Thanks for the update! I removed it and saw no issues but wanted to confirm.
