### ISSUE TITLE
rollData type is inconsistent

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#8]
I hope you'll forgive another question.  

At the end of the #makeRoll function there is an else that is potentially setting rollData without keys for `value`, `modifier`, and `result`. The comment says the intent is to save this for later. Is this used later ?

`getRollResults()` & `this.#DiceWorld.onRollComplete` expects rollData entries to have `value`, `modifier`, and `result` keys.  Entries that lack these keys will break the expected behavior.

```
if ( hasGroupId ) {
 Object.assign( this.rollData[groupId].rolls, rolls )
} else {
 const index = this.#groupIndex
 // save this roll group for later
 const rollGroup = { ...notation, rolls }
 this.rollData[index] = rollGroup
 ++this.#groupIndex
}
```

**Comment by frankieali** [comment]
Ok, so #makeRoll is used by `.roll()`,`.add()` (and `.reroll()` which calls `.add()`). This was an attempt to keep the code DRY. So `.#makeRoll` will create a new roll group unless a `groupId` is passed in, which is the case when using `.add` and `.reroll`. So the if statement in `.#makeRoll` will add new rolls to the group defined by `groupId` `} else {` put all _new rolls_ into the rollData array using `this.#groupIndex` as the new groupId. Once the physics simulation has completed then the results are calculated in `.#DiceWorld.onRollComplete`. 

`.getRollResults()` is more of a connivence method I added to get the rollData without having to setup a OnRollComplete callback. It's not connected to anything else at the moment. I did not consider the possibility that it could be called before the physics simulation completed.

To this end I have a code change in the works that updates `.roll(), .add() and .reroll()` method to return a promise instead of the class config object. This way one could write `DiceBox.roll('5d6').then(results => {...})) without the need to create a OnRollComplete callback.

**Comment by clevett** [comment]
I'll close this issue for now. I resolved it in my ts code by adding the missing keys.

```
// save this roll group for later
const addResult = rolls.map(roll => ( { ...roll, result: 0 } ) )
 const rollGroup = { ...notation, rolls: addResult, value: 0, modifier: 0 }
```
